FROM golang:latest

RUN apt-get update
RUN apt-get install vim -y
RUN go get "github.com/go-sql-driver/mysql"
RUN go get "github.com/gin-gonic/gin"
RUN go get "github.com/google/uuid"
RUN go get "github.com/gin-contrib/cors"
